scripts/flash_can.py, src/generic/canbus.c
Use Klipper's nodeid to canbus_id scheme (`canbus_id = nodeid * 2 + 0x100`).  Instead, use a nodeid offset of 128 to avoid collisions with Klipper.
Using different nodeids instead of a different nodeid mapping may be easier for developers and users to understand.  Currently klippy uses nodeids starting at 0, console.py in the Klipper repo uses nodeids starting at 64, and this PR would set canboot to use nodeids starting at 128.
Note that this change would break flash_can.py for any existing canboot installations.
-Kevin
=> Use Klipper's nodeid to canbus_id scheme

Makefile
Build size is likely more important than CPU performance for a bootloader.  So, instruct gcc to optimize for size by default.
On my fedora build of the stm32f103 code (with led support) going from -O2 to -Os changed the build from 4080 bytes to 3368 bytes (a ~20% reduction in size).
-Kevin
=> Makefile: Build with -Os instead of -O2

src/canboot_main.c, src/generic/armcm_boot.c, src/generic/misc.h, src/stm32/stm32f0.c, src/stm32/stm32f1.c
This PR simplifies the `jump_to_application()` code by utilizing the existing "request signature" system.  The code can set a "request application startup" flag, then do a full cpu reset, and then launch the application in the early bootup code (before doing any cpu init).  This should also make cpu initialization more reliable.
I chose the `REQUEST_START_APP` code randomly (`head -c 8 /dev/random | hexdump -C`).
-Kevin
=> Do hardware reset before application start

src/canboot_main.c, src/stm32/Kconfig, src/stm32/flash.c, src/stm32/flash.h
I expect it will be difficult for many users to determine if they need a 1K or 2K page size on the stm32f103.  As near as I can tell, this can be auto-detected by inspecting the flash size on the stm32f103 - only devices with 256K or more of flash have a 2K page size.
This PR updates the code to attempt to auto-detect the flash page size at runtime.
-Kevin
=> Autodetect stm32f103 flash page size

src/bootentry.c, src/generic/armcm_timer.c, src/generic/misc.h, src/led.c, src/sched.c, src/sched.h, src/stm32/stm32f0.c, src/stm32/stm32f0_timer.c
Explicitly enable the timer (via a new `timer_setup()` call from sched_main.  This is a minor change that saves a few bytes in the final binary.
-Kevin
=> Call timer_setup() from sched_main()

src/flashcmd.c, src/stm32/Kconfig, src/stm32/flash.c, src/stm32/flash.h, src/stm32/stm32f4.c, src/stm32/usbotg.c
This adds initial support for F4 series devices.  While STM32F4 devices support DFU, many boards have a design error making them incapable of entering the DFU bootloader.  The `flash_sdcard` method provides a workable alternative for many of these boards, however we are seeing more boards ship using SDIO.  Also included is canbus support.
On the F4 series, flash is organized into "sectors" rather than "pages".  The method for erasing and writing is a bit different, thus the most significant change to support F4 devices is in `flash.c`.  Unlike pages, we do not have to write an entire sector all at once.  That said, a sector must be erased before we can write to it, thus it is necessary to detect when a write begins at a sector boundary.   Sector organization is a bit strange...there there …
=> stm32: Add support for STM32F4 devices

Makefile, scripts/buildcommands.py, src/Kconfig, src/Makefile, src/initial_pins.c, src/initial_pins.h
Some boards require gpio setup in order to use USB.  This ports the "initial pins" capability from Klipper to support that.
-Kevin
=> Add support for initial pins

scripts/buildbinary.py, src/stm32/Kconfig, src/stm32/Makefile
This allows stm32 f0 and f1 devices to support either 4K or 8K bootloader size.  It also adds a build check to verify the final binary fits within the requested size.
I have an stm32f042 device with only 32KiB of flash - using a 4K bootloader size really helps on that device.
-Kevin
=> Support 4KiB application start

src/initial_pins.c
It seems the initial_pins code is adding a few hundred bytes to the final binary size even when not in use.  I didn't realize that.  It's easy to add a gcc check to optimize it out.  If all looks okay, I'll add the same check to Klipper.
-Kevin
=> Add compile time check to initial_pins to reduce binary size

src/bootentry.c, src/flashcmd.c, src/generic/armcm_boot.c, src/generic/misc.h, src/sched.c, src/stm32/Kconfig, src/stm32/flash.c, src/stm32/flash.h
This PR is a series of minor things I noticed when debugging the stm32f042 yesterday.  The main change is the last patch, which converts the code to write each flash "block" individually.
A high-level summary:
1. Rework the `check_application_code()` check to just check that the application stack pointer looks valid.  This will, hopefully, do a slightly better job of entering the bootloader when no app is installed.
2. Move the `flash_read_block()` out of flash.c - as it's going to be the same code on all arm machines.  May make porting flash.c to other architectures slightly easier.
3. Avoid using read-modify-write updates to `FLASH->CR`.  Directly writing the desired settings produces better code and is easier to debug (as it's hard to reason about the state of the register when it's …
=> Write each block individually ; no need for pages

src/stm32/flash.c
It occurred to me that there is a straight forward way to report the number of pages from the "eof" command.  So, this just restores the previous (documented) behavior of the "eof" command.
-Kevin
=> Report pages written from "eof" command

src/stm32/Kconfig
I inadvertently changed the default of f0/f1 to 4KiB application start in commit d6c874b0.  This restores the default of 8KiB (which I suspect is less likely to confuse new users).
While I was at it, I also enabled a 16KiB app start on F4.  The default remains 32KiB.
-Kevin
=> Default to 8KiB app start on f0/f1 ; Allow 16KiB on f4

src/stm32/Kconfig, src/stm32/Makefile, src/stm32/flash.c, src/stm32/stm32g0.c
This adds support for the stm32g0b1 chip.  I've successfully tested this on my btt-skr-mini-e3-v3.
The stm32f2 flash hardware appears to be identical to stm32f4.  (And, in general, the stm32f2 hardware is very similar to the f4 hardware.)  I don't have an stm32f2, but I think it is safe to enable.
The stm32f070 and stm32f030 appear similar to stm32f103.  I made the minor code changes for it and enabled it.  I don't have these chips, however, so I did not test it.
-Kevin
=> Support for additional stm32 chips

lib/lpc176x/device/LPC17xx.h, lib/lpc176x/device/system_LPC17xx.c, lib/lpc176x/device/system_LPC17xx.h, lib/lpc176x/lpc176x.patch, src/Kconfig, src/lpc176x/Kconfig, src/lpc176x/Makefile, src/lpc176x/chipid.c, src/lpc176x/flash.c, src/lpc176x/flash.h, src/lpc176x/gpio.c, src/lpc176x/gpio.h, src/lpc176x/internal.h, src/lpc176x/main.c, src/lpc176x/serial.c, src/lpc176x/usb_cdc_ep.h, src/lpc176x/usbserial.c
This adds experimental support for the lpc1768 (and hopefully lpc1769) MCUs.   There are some things I discovered with this implementation, and thus there may need to be some refactoring before I merge.
- As previously mentioned, the IAP write addresses must be on a 256 byte boundary.  Rather than increase block size (and thus the size of the rx and tx buffers) I just buffered the data in flash.c.  That said, I worked the implementation to accept a larger block size and skip the buffer if we want to move in that direction.
- I noticed that the `FLASHTIM` field in the `FLASHCFG` register was set to 3.  According to the datasheet this should be set to 4 for 100MHz (and 120MHz) processors.  I changed that since my assumption is the bootloader is going to require the "flash accelerator" to be …
=> Add support for lpc176x devices

src/deployer.c
I was changing over my huvud 0.50 boards from "hid bootloader" to CanBoot using the "deployer" function.  Unfortunately, I ran into an issue where CanBoot failed to deploy and the board was left without a functional bootloader.  I connected openocd to the swd lines and dumped the flash.  It showed that the deploy tool failed after flashing 1356 bytes of the total 3590 bytes.  It looks like the reset line was glitching (likely when I was applying the reset jumper on the huvud 0.50 board) which caused the mcu to restart many times in a short period.  It looks like the deployer got far enough into its processing to erase the existing bootloader, but didn't get enough time to fully flash the new binary before a reset occurred.
To avoid this type of failure, this PR adds a 100ms delay before …
=> Wait 100ms before overwriting existing bootloader in deployer

src/bootentry.c
I have an lpc1768 test board that always seems to enter CanBoot when first powered on.  It seems that when the board first powers up the power may not be fully stable and it can result in one or more resets in the first few milliseconds.  Changing CanBoot to ignore resets in the first 10ms fixes this for me.  Thus, after this PR, to enter the bootloader, the "double click" time must be between 10ms and 500ms.
-Kevin
=> Don't consider a reset in less than 10ms a double click

src/rp2040/Kconfig
Small cleanup: make deployer build optional. Synchronize  rp2040 deployer KConfig settings with other targets.
Signed-off-by: Alex Malishev <malishev@gmail.com>
=> rp2040: make deployer build optional

src/stm32/flash.c
Issue: CanBoot and the deployer were able to erase memory but not to write it write right afterwards on STM32F723.
Fix: Add a flash lock/unlock sequence after erasing and before writing to the flash memory in flash_write_block(). Shouldn't be destructive for the other supported STM32 processors.
Tested on STM32H723, STM32H743 and STM32F407.
Signed off by: Robin Gay <robingay67@gmail.com>
=> flash.c: fix write error for STM32H72x

src/stm32/stm32g0.c
stm32g0.c: Disable UCPD on boot
The UCPD is not used with Katapult but it can result in unexpected behaviour on certain pins due to the internal pull resistors unless disabled.
Signed-off-by: Luke Harrison looxonline@gmail.com
=> stm32g0.c: Disable UCPD on boot

src/stm32/Makefile
In order for users to write `Katapult.bin` to MCU for the first time through DFU (`make flash`), this content was directly copied from Klipper, only the path of `Klipper.bin` was modified to `Katapult.bin`. I noticed that rp2040 has a rule for `make flash` from klipper, so I also copied the rule of STM32 directly.
This PR can be used by the user to directly write `Katapult.bin` to the MCU using the `make flash` command in path "Katapult"
=> stm32: dfu-util "make flash" rules for stm32 mcu

src/stm32/Kconfig
Certain STM32 Nucleo development boards (eg. F429Zi) come pre-installed with a 32MHz quartz crystal, which is now exposed as an option when selecting STM32 chips.
=> stm32/Kconfig: Add option for 32MHz crystals
